### ISSUE TITLE
strip tags of hashes

### ISSUE THREAD

**Issue by fbstj** [Palanaeum/palanaeum#26]
the [tag list](https://wob.coppermind.net/tags/) has an event tagged with `##needsaudio` which is [this](https://wob.coppermind.net/events/25-paris-signing/) event. such tags shouldn't be creatable, the validation should strip leading/trailing/all? hashes from tags.

**Comment by yrsegal** [comment]
Should tag names only allow characters matching the following?

```regex
[A-Za-z0-9\-_\s]
```

**Comment by yrsegal** [comment]
e4bc30a5781e70c190df54d8c122503900295279
