### ISSUE TITLE
pagination back button seems to be broken

### ISSUE THREAD

**Issue by fbstj** [Palanaeum/palanaeum#39]
on multiple pages (eg [events](https://wob.coppermind.net/events/?page=5&) & [recent](https://wob.coppermind.net/recent/?page=91&mode=created)) the forward `>` button takes you a page forward but the back `<` button takes you to the start as it doesn't fill in the `page.prev_page_number at

https://github.com/Palanaeum/palanaeum/blob/999853d2d0327f890fe665e23dcb14a4e7d8988c/palanaeum/templates/palanaeum/pagination_nav.html#L3

this results in `?page=&` instead of a back link, which takes you to the first page

**Comment by mhalverson** [comment]
I put up a pull request that (based on the docs) I think will fix this issue. However, I haven't loaded any test data into my dev instance of Palanaeum, so I have not verified that the actual behavior matches the docs.

Has anyone written a script for loading test data into a dev instance?

**Comment by m-strzelczyk** [comment]
No, we don't have any script populating the database. It should be enough to create some empty events and lower your page length in user settings. I'll keep in mind that some random data generator would be useful.
