### ISSUE TITLE
advanced searching an unknown term finds every entry

### ISSUE THREAD

**Issue by fbstj** [Palanaeum/palanaeum#43]
Following [this link](https://wob.coppermind.net/adv_search/?query=Lhin&date_from=2003-12-05&date_to=2018-06-28) should show 0 results, as [this query](https://wob.coppermind.net/adv_search/?query=Lhin) does

the date ranges are finding *every* entry and aren't being removed by the lack of results from the word query

**Comment by IAmEki** [comment]
Solved by pull request #58.
