### ISSUE TITLE
Change functionality of Share button

### ISSUE THREAD

**Issue by jofwu** [Palanaeum/palanaeum#48]
The Share button currently sends you to a direct link of the entry. This functionality doesn't seem very helpful to me. First because the "entry number" button already accomplishes this. Second because the only reason I can think that one might use this button is if they want to paste the URL somewhere. Currently to do this, you have to either right click and copy the link, or else click share to let the page load and copy from the address bar. Neither is really necessary if clicking the Share button simply copies the URL to the clipboard.

Downsides I see are (1) perhaps the distinction between Share and Copy would confuse people and (2) if the ultimate plan is to support specific methods of sharing (e.g. 17S, Facebook, Twitter, etc.) then this is perhaps a waste of time.

**Comment by IAmEki** [comment]
This seems to have been changed at some point, so "share" copies the direct link straight away. Could probably be considered closed.
