### ISSUE TITLE
make the pagination ... expand or ask for page to go to

### ISSUE THREAD

**Issue by fbstj** [Palanaeum/palanaeum#55]
fixing #35 resulted in a `...` being added to shorten the number of pages to +-3 around the current, first, and last pages. it currently acts like a button/link but does nothing when clicked. it may be better to remove the `<a>` entirely, or instead to make the `...` expand into more pages or show the full list or ask for a particular page number

**Comment by burnhamaj** [comment]
I'm going to tackle this. I hope to be able to reveal all pages when the ellipsis is clicked, but if I can't get that working I'll just make it not a link.

**Comment by burnhamaj** [comment]
Merged in commit 9898a55. I believe this can be closed.
