### ISSUE TITLE
show the page number selector at the top as well as the bottom

### ISSUE THREAD

**Issue by fbstj** [Palanaeum/palanaeum#9]
on specifically the search box it would be nice if the paginator was shown on the right of the screen opposite the Advanced Search title

![image](https://user-images.githubusercontent.com/19763/39303224-3c3c9828-494d-11e8-9b2e-5133be9f7ecc.png)

**Comment by mhalverson** [comment]
I took a look through the commit log -- has this really been done? If not, I'll take a look at it in November :)
